type Query {
    getProduct(id: ID!): Product
    getAllProducts(page: Int, limit: Int): [Product]!
}

type Mutation {
    createProduct(productInfo: ProductInput): Product
    updateProduct(id: ID!, productInfo: ProductInput): Product
    deleteProduct(id: ID!): Product
}