name: CI/CD with Docker and Render
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove old Docker images
        run: |
          docker images --filter=reference="*:latest*" -q | xargs -r docker rmi

      - name: Build Docker image
        run: |
          docker build -t ecommbackend .
          docker tag ecommbackend "${{ secrets.DOCKER_USERNAME }}/ecommbackend:latest"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/ecommbackend:latest"
